name: Run tests and upload coverage

on: push

jobs:
    test:
        name: Run tests and collect coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js 21.x
              uses: actions/setup-node@v4
              with:
                  node-version: 21.x
            - name: Install dependencies
              run: npm ci
            - uses: federicocarboni/setup-ffmpeg@v3
              id: setup-ffmpeg
              with:
                  ffmpeg-version: release
                  github-token: ${{ secrets.GITHUB_TOKEN }}
            - run: ffmpeg -version
            - name: Run tests
              run: npx vitest run --coverage

            - name: Upload results to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
