name: Auto Pull Request

on:
    push:
        branches:
            - 'e/*'
            - 'f/*'
            - 'b/*'
            - 't/*'

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21'

            - name: Install dependencies
              run: |
                  cd .github/scripts
                  npm install

            - name: Run PR script
              run: node .github/scripts/create-pr.mjs
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
